# Generated by Django 2.1.7 on 2019-04-04 17:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.PositiveIntegerField(verbose_name='Column')),
                ('row', models.PositiveIntegerField(verbose_name='Row')),
                ('column_span', models.PositiveIntegerField(verbose_name='Column span')),
                ('row_span', models.PositiveIntegerField(verbose_name='Row span')),
                ('advanced', models.CharField(max_length=3, verbose_name='Advanced')),
                ('font_size', models.PositiveSmallIntegerField(verbose_name='Font size')),
                ('direction', models.BooleanField(verbose_name='Direction')),
                ('vertical_align', models.CharField(blank=True, choices=[('t', 'Top'), ('m', 'Middle'), ('b', 'Bottom')], default='m', max_length=1, verbose_name='Vertical align')),
                ('horizontal_align', models.CharField(blank=True, choices=[('l', 'Left'), ('c', 'Center'), ('r', 'Right')], default='h', max_length=1, verbose_name='Horizontal align')),
                ('width', models.PositiveIntegerField(verbose_name='Width')),
                ('height', models.PositiveIntegerField(verbose_name='Height')),
                ('value', models.CharField(max_length=500, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_in_load', models.PositiveIntegerField(verbose_name='Column in load')),
                ('column_in_plan', models.PositiveIntegerField(verbose_name='Column in plan')),
                ('name_in_load', models.CharField(max_length=100, verbose_name='Name in load')),
                ('name_in_plan', models.CharField(max_length=100, verbose_name='Name in plan')),
                ('load_type', models.BooleanField(default=False, verbose_name='Load type')),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PlanFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/plans/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of setting sender request')),
                ('answer_date', models.DateTimeField(default=None, null=True, verbose_name='Date of getting receiver answer')),
            ],
        ),
        migrations.CreateModel(
            name='RequestResultType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScienceDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScienceTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=3)),
                ('course', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('row_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/loads/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='result',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pback_main.RequestResultType'),
        ),
        migrations.AddField(
            model_name='request',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pback_main.RequestType'),
        ),
        migrations.AddField(
            model_name='field',
            name='type_of_load',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pback_main.Load'),
        ),
    ]
