# Generated by Django 2.1.7 on 2019-04-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pback_main', '0002_auto_20190404_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
